import type { NextPage } from 'next';
import Head from 'next/head';
import useIndex from './../data/hooks/pages/useIndex.page';
import styles from '../ui/styles/Home.module.css';
import PostsList from '../ui/components/PostList/PostList';

const Home: NextPage = () => {
  const { posts } = useIndex();

  return (
    <div className={styles.container}>
      <Head>
        <title>TreinaBlog</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PostsList posts={posts} />
      </main>
    </div>
  );
};

export default Home;
